// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUG0V6DpjGGdUuBiKPFNKmUdrZP1dkGIs',
    appId: '1:771639011569:web:fbefc62c8c335ecf792150',
    messagingSenderId: '771639011569',
    projectId: 'cne-watch2earn',
    authDomain: 'cne-watch2earn.firebaseapp.com',
    storageBucket: 'cne-watch2earn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByEm21sFAKx7pQp2RQ0hiZeNWgAM8k4EE',
    appId: '1:889552494681:android:e93d4e94dc607b29681148',
    messagingSenderId: '889552494681',
    projectId: 'coinnewsextratv-9c75a',
    storageBucket: 'coinnewsextratv-9c75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXdv9MAUpjneGnR4P_zizdek720NFRNs',
    appId: '1:889552494681:ios:c7dd062e4e71fe6e681148',
    messagingSenderId: '889552494681',
    projectId: 'coinnewsextratv-9c75a',
    storageBucket: 'coinnewsextratv-9c75a.firebasestorage.app',
    iosBundleId: 'com.coinnewsextratv.cnetv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWXdv9MAUpjneGnR4P_zizdek720NFRNs',
    appId: '1:889552494681:ios:c7dd062e4e71fe6e681148',
    messagingSenderId: '889552494681',
    projectId: 'coinnewsextratv-9c75a',
    storageBucket: 'coinnewsextratv-9c75a.firebasestorage.app',
    iosBundleId: 'com.coinnewsextratv.cnetv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUG0V6DpjGGdUuBiKPFNKmUdrZP1dkGIs',
    appId: '1:771639011569:web:9bd7aea2437f14c9792150',
    messagingSenderId: '771639011569',
    projectId: 'cne-watch2earn',
    authDomain: 'cne-watch2earn.firebaseapp.com',
    storageBucket: 'cne-watch2earn.firebasestorage.app',
  );
}
